version: '3'

services:
  api:
    container_name: save-my-money-api
    build: 
      context: .
    volumes:
      - .:/usr/src/save-my-money
      - /usr/src/save-my-money/node_modules
    ports:
      - "3000:3000"
    tty: true
    networks:
      - save-my-money-network
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: postgres:15.1
    container_name: save-my-money-db
    environment:
      - POSTGRES_USER=save-my-money-user
      - POSTGRES_PASSWORD=save-my-money
      - POSTGRES_DB=save-my-money
    networks:
      - save-my-money-network

  
networks:
  save-my-money-network:
    driver: bridge